### ISSUE TITLE
Locate Button not touchable on Android Device

### ISSUE THREAD

**Issue by cblandy** [Esri/map-tour-storytelling-template-js#41] opened 2015-06-18 19:00 UTC
I have created a hosted Story Map Tour (http://cosmos.surrey.ca/external/tools/DoorsOpen2015/). On the desktop the locate button works as expected. However on my Google Nexus 5 the locate button does not function. It doesn't even seem to be touchable. IS this a bug or something the I can modfiy in code or configuration.
Note: I use a basemap that is in our (City of Surrey) own portal.

Cameron

**Comment by glazou** [comment] 2015-06-18 19:35
Hi Cameron,
Seems to works on my Nexus 5 in Chrome. Are you using Chrome?
If you go to let's say google.com/maps will it let you use your location?
First time you click on the button, you should have a popup that appear at the bottom of the screen and ask you to confirm you want to let the app use your location. Did you saw it?

In Chrome, you may want to check Settings > Site Settings > Location to see if Location is not disabled or not allowed on your site.

**Comment by cblandy** [comment] 2015-06-18 19:51
Yes, I am using Chrome (vers. 43.0.2357.92)). I also tried on Firefox, same result. I cleared all of my site settings but it doesn't not even ask if I want to using location services. It is like the button is inactive.

Google Maps found my location.

**Comment by glazou** [comment] 2015-06-18 19:53
Must be the app then. Have you made any customization to the app?
Does the button works on that one http://www.arcgis.com/apps/MapTour/index.html?appid=049e96a487f84c668819f93595b0adfe ?

**Comment by cblandy** [comment] 2015-06-18 20:31
Yes, I have made some customizations to the app, nothing too major. I did get it to work (once) on Chrome and it works on Firefox but it seems a little flaky. I am using Android 5.1 so I suspect that could be the cause. Which version are you using on your Nexus 5? I have been able to get it to work once by turn off location on the phone turning it back and agreeing to the Google Location services. It shows the location once but not subsequently.

**Comment by glazou** [comment] 2015-06-18 20:45
I am on 5.1.1, same Chrome version.

I have been able to reproduce. The app is just not behaving good enough, while the app is asking the phone for it's location, if it take a while, there is no indication that this is in progress in the app.

If I disable location and re-enable it, it takes a while for the phone to get my location (like 2mn). Once the phone get a location, looks like the app is not able to use it, even reloading the tab or closing it and reopening doesn't help, whereas GMaps in the browser has no problem.

I am going to take a look into this for our upcoming release (July 9th) and let you know how it goes in the next days. Thanks for the feedback.

**Comment by cblandy** [comment] 2015-06-18 20:58
OK. Thanks for checking into to this for me. I look forward to trying out the new version in a few weeks.

**Comment by glazou** [comment] 2015-06-19 20:21
I should have a fix in the next release, stay tuned.

**Comment by RupertEssinger** [comment] 2015-06-30 21:27
I couldn't repro this original issue on my Android device (Google Nexus 7 tablet - Android 4.4.4). For me Location button has no prob on PRD or DEVEXT

**Closed** 2015-07-09 01:36 UTC
Labels: bug
